# Generated by Django 6.0.6 on 2026-07-09 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('Product 1', 'Product 1'), ('Product 2', 'Product 2'), ('Product 3', 'Product 3')], max_length=100)),
            ],
        ),
    ]
