# Generated by Django 6.0.6 on 2026-07-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Epower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epower',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10),
        ),
    ]
